Refactor empty state and rearrange components routes alphabetical
CodeTanzania/emis-web pull request #4
Opened 2019-01-26 07:29 UTC by mkumbobeaty

2019-01-26 08:41 UTC, BenMaruchu requested changes
Hey @mkumbobeaty  Nice work. There are some few things needs updating, if you don't understand it please ask.

2019-01-26 08:41 UTC, BenMaruchu commented on src/layouts/BaseLayout.js
> +  /* end of assissment components */
there is a typo here

2019-01-26 08:41 UTC, BenMaruchu commented on src/layouts/BaseLayout.js
> +  /* end of assissment components */
Also I have a suggestion 

we can use separators like this
```js
/* Assessments routes */
  '/assessments': { name: 'Assessments', title: 'Assessments module' },
  '/assessments/indicators': {
    name: 'Indicators',
    title: 'Indicators for monitoring assissment',
  },
  '/assessments/questionnaires': {
    name: 'Questionnaires',
    title: 'List of questionnaires',
  },
  '/assessments/questions': {
    name: 'Questions',
    title: 'List of questions',
  },
  '/assessments/responses': {
    name: 'Responses & Observations',
    title: 'Assissment Responses and observations',
  },

/* Geographical Routes */
...
```

let remove `end of something`  line

2019-01-26 08:41 UTC, BenMaruchu commented on src/layouts/BaseLayout.js
> +  /* end of assissment components */
Also there are many typos in this file ... 
it is supposed to be `assessments` and not `assissment`

2019-01-26 08:41 UTC, BenMaruchu commented on src/layouts/BaseLayout.js
> +  /* end of assissment components */
Also on the separation comments please use `routes` and not `components` since these are routes

2019-01-26 14:34 UTC, BenMaruchu commented
@mkumbobeaty  can you pull changes from develop and fix if there is any issues cause I can see conflicts here

2019-01-26 14:35 UTC, mkumbobeaty commented
Oky

On Sat, 26 Jan 2019 at 17:34, Benson Maruchu <notifications@github.com>
wrote:

> @mkumbobeaty <https://github.com/mkumbobeaty> can you pull changes from
> develop and fix if there is any issues cause I can see conflicts here
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CodeTanzania/emis-web/pull/4#issuecomment-457835887>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AT2pXfmAxWA79PEzYBwXpmqUYfzZ_OqRks5vHGeHgaJpZM4aUCq_>
> .
>

2019-01-27 20:44 UTC, BenMaruchu approved these changes

2019-01-27 20:45 UTC, merged